import { Difficulty } from "@/types/difficulty";

export const DIFFICULTIES: Difficulty[] = [
  {
    id: "easy",
    name: "易しい",
    icon: "☆",
    color: "#27AE60",
    salmonCount: 2,
    initialSpeed: 1000,
    speedUpInterval: 60000,
    speedUpRate: 0.95,
    hasGarbage: false,
  },
  {
    id: "normal",
    name: "普通",
    icon: "▶",
    color: "#2E86C1",
    salmonCount: 4,
    initialSpeed: 800,
    speedUpInterval: 45000,
    speedUpRate: 0.92,
    hasGarbage: false,
  },
  {
    id: "hard",
    name: "難しい",
    icon: "◆",
    color: "#E67E22",
    salmonCount: 6,
    initialSpeed: 600,
    speedUpInterval: 30000,
    speedUpRate: 0.88,
    hasGarbage: true,
  },
  {
    id: "extreme",
    name: "激ムズ",
    icon: "★",
    color: "#C0392B",
    salmonCount: 8,
    initialSpeed: 400,
    speedUpInterval: 20000,
    speedUpRate: 0.85,
    hasGarbage: true,
    garbageFrequency: "high",
  },
];
